CREATE SCHEMA IF NOT EXISTS management;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE management.users(
  id VARCHAR DEFAULT uuid_generate_v4() PRIMARY KEY,
  name VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

